layout_spectrum: 0.8154122
color:
  saturation: 0.3213983
  lightness: 0.8271166
  brandStrength: 0.6891664
  rhythmicContrast: 0.2640456
typography_spectrum: 0.7763503
name: Christianhorsengtattooing
